# Generated by Django 4.1.8 on 2023-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(max_length=255)),
                ('precautions', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='disaster_images/')),
            ],
        ),
    ]
