# Generated by Django 4.1.8 on 2023-04-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='types_of_disaster_images/'),
        ),
    ]
