# Generated by Django 4.1.8 on 2023-04-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster_report',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='disaster_images/'),
        ),
    ]
