# Generated by Django 4.1.8 on 2023-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_customuser_id_alter_service_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_address', models.CharField(max_length=100)),
                ('hospital_type', models.CharField(max_length=100)),
                ('hospital_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_detail', models.CharField(max_length=100)),
                ('shop_type', models.CharField(max_length=100)),
                ('shop_contact', models.CharField(max_length=100)),
            ],
        ),
    ]
