# Generated by Django 4.1.8 on 2023-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_hospital_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('authority', 'Authority'), ('volunteer', 'Volunteer'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
